# Generated by Django 2.2.12 on 2021-12-26 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessWorker',
            fields=[
                ('WorkerID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=30)),
                ('Number', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=1)),
                ('Address', models.CharField(max_length=80)),
                ('Document', models.FileField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Number', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=80)),
                ('Email', models.EmailField(max_length=30, unique=True)),
                ('roll_num', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('Coupon_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(default=None)),
                ('Breakfast', models.IntegerField(default=0)),
                ('Lunch', models.IntegerField(default=0)),
                ('Evening_snacks', models.IntegerField(default=0)),
                ('Dinner', models.IntegerField(default=0)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintRecord',
            fields=[
                ('Complaint_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Subject', models.TextField(default='', max_length=50)),
                ('Description', models.TextField(max_length=200)),
                ('Status', models.CharField(default='not seen', max_length=20)),
                ('Comments', models.CharField(default='', max_length=30)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Student')),
            ],
        ),
    ]
