# Generated by Django 2.2.12 on 2021-12-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.FileField(upload_to='mess_menu')),
            ],
        ),
        migrations.AlterField(
            model_name='messworker',
            name='Gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='M', max_length=1),
        ),
    ]
