# Generated by Django 2.2.12 on 2021-12-27 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20211226_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintrecord',
            name='Date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='complaintrecord',
            name='Comments',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='complaintrecord',
            name='Status',
            field=models.CharField(choices=[('Not seen', 'Not seen'), ('seen', 'seen')], default='not seen', max_length=20),
        ),
        migrations.AlterField(
            model_name='messworker',
            name='Document',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='messworker',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
